language: python
python:
- '3.3'
install: pip install -r requirements.txt
script: true
deploy:
  provider: openshift
  user: p.horacek94@gmail.com
  password:
    secure: 5RM6B2uIzwHy24jnl5Whx76HqrrlPZ7bi7fq64OFXowWrjbngZeC363s9klRcCHPnf+2EAtwe1N1TEbMeWtrzmjk/91/dmbOpAvRIA02vdAcW/M22R3ULvnYnMkE2ht6fkaComqTEp80FYkEcK89YEZF4E416HSUJJg+YCuH5gXFlzV3InNaqH9opzmzutOZWpAUQLR+ZUQJHN3ns9imhLmXroa6Eo7mz5BsAdwqBBa5DKjHsHTfJr2FhXckVYbOHqfOE72yZ5wWzEBpq8dJl2AgMv86wVDNTpU9S2UH72djKrj/Q9angveGmpnHupcmdhAee8dSUApIoHARLGMR5ga/k521onojMfItJwWafkGvO1UWMoZmVMwnenBnzLCy3xWwb+bWO8Lkle9bmCFLp/8U755yTUM1qd/mTWUhNuhv952jt9AnSL8lTuUEFxNqdVUuwsm8X2Zh7LroMXv40Snq+46J3JzgY5qGQ2fms4htd1mF61ESl3hZH+1UAFPRo7922IrjJoKOQYYthsgHujQqWcaaIU2ZNUIQ2q+uVvsijkr5HqWDHqOXbw6RuywTe536bjfcsrlfOGzk31rUy/+FTCdj39KkGJv/HaQ4aM/AnpvE71tpDzfECAZ5vTTeXLAwXtqtmkG3dBJApGBI0KgEwPvWKFLha/3jt8SLH/I=
  app: vytvarna
  domain: petrhoracek
  on:
    repo: phoracek/vytvarna.cz
