language: python
python:
- '3.3'
install: pip install -r requirements.txt
script: true
deploy:
  provider: openshift
  user: p.horacek94@gmail.com
  password:
    secure: Hl6J+qh4iVmQm1Mz/ahmu7IuVC3gTkvk916y5lMV84ocBkbn91z/SGGTTUoDQ5L2Hl+pqugZbgwqy+L06wk0Cakyjz+T3+wCbJdiK4lzQBERWFZDiujaIWTr8gZsNdrQOrEyXgQNQ3B8dcRypDXNBcvrk/zLMrkTKtZE/iWjSxKzelsPzii+n7imHlPLB35fgT3YMDWA1slQLJ4KJpEFw3AWL2NPtJ6VrYORk+QNrrjtknght4WkJJiqGpxostNYhp1Ehp5QEeK6dCpxSnr1EMNMfE7mpeWWN2MRhl7z73FlPiyAIOXjfCZcqGucXOFnzQ3BjttbRANEgNExCQNGptb0FVEXSbM9Ub59OMeLJ4xYb6sQhIJ2UNbL3zIDLz+LfLOjn6z6R7oJaWUd+s12E4tNSCIbfLmnp0ssKPTxYxzDC4/DbgTHOt8czQkAP031Ie2TuCWS0iEzjilqlviBzNQ7teo3Q2sCfBqzYDNkMlkOLN9fqm0gaE4WEa6QV7T2u5PvATOHSbJOFektsNuGba42weGOgrYYZVSZXY6TIm4U+9r/kDJzYIkw8vVNc0nMpg01XoLzA/FdL8adLObqY0e9syma3B8wvH1Q9jP0VcarUdg4imXSnhr8+eZTp0AFihkYoF1v5oGBpcRcAwwZxvTyHk++LbBS3KuE7uegRhw=
  app: vytvarna.cz
  domain: petrhoracek
  on:
    repo: phoracek/vytvarna.cz
